[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
lexer = { path = "../lexer" }

[dev-dependencies]
parser = { path = "../parser" }
lexer = { path = "../lexer", features = ["lexer"] }
